export const USER_LOGIN_REQ = 'USER_LOGIN_REQ';
export const USER_LOGIN_SUCC = 'USER_LOGIN_SUCC';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQ = 'USER_REGISTER_REQ';
export const USER_REGISTER_SUCC = 'USER_REGISTER_SUCC';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQ = 'USER_DETAILS_REQ';
export const USER_DETAILS_SUCC = 'USER_DETAILS_SUCC';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_UPDATE_REQ = 'USER_UPDATE_REQ';
export const USER_UPDATE_SUCC = 'USER_UPDATE_SUCC';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
