export const USER_LOGIN_REQ = 'USER_LOGIN_REQ';
export const USER_LOGIN_SUCC = 'USER_LOGIN_SUCC';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQ = 'USER_REGISTER_REQ';
export const USER_REGISTER_SUCC = 'USER_REGISTER_SUCC';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
